<?php
/**
 * Created by PhpStorm.
 * User: zhanglei02
 * Date: 2018/4/19
 * Time: 下午6:18
 */
namespace Douyasi\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * 分类模型
 */
class ArticlesUser extends Model
{
    protected $table = 'articles_user_';

    protected $primaryKey = 'id';

    protected $fillable = [
        'uid',
        'cid',
        'slug',
        'description',
    ];

    public function setTable($uid)
    {
        $this->table = $this->table.($uid % 10); // TODO: Change the autogenerated stub
    }


	public function category()
    {
        //模型名 外键 本键
        return $this->hasOne('Douyasi\Models\Category', 'id', 'cid');
    }

}
